apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sh: |
    #!/bin/sh
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      SELECT 'CREATE DATABASE catalogdb'
      WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'catalogdb')\gexec
    EOSQL
    echo "host    all             all             0.0.0.0/0               trust" >> "$PGDATA/pg_hba.conf"
    echo "host    replication     all             0.0.0.0/0               trust" >> "$PGDATA/pg_hba.conf"
    echo "wal_level = replica" >> "$PGDATA/postgresql.conf"
    echo "max_wal_senders = 8" >> "$PGDATA/postgresql.conf"
    echo "max_replication_slots = 8" >> "$PGDATA/postgresql.conf" 